/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p24;

/**
 *
 * @author 18PROGB0163
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */

    public Inicio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbCm = new javax.swing.JRadioButton();
        rdbMl = new javax.swing.JRadioButton();
        lblResM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtM = new javax.swing.JTextPane();
        txtH = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        rdbMin = new javax.swing.JRadioButton();
        rdbSeg = new javax.swing.JRadioButton();
        lblResH = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGr = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtKg = new javax.swing.JTextPane();
        rdbKg = new javax.swing.JRadioButton();
        rdbGr = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Conversiones.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Metros.");

        rdbCm.setText("Centimetros.");
        rdbCm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCmActionPerformed(evt);
            }
        });

        rdbMl.setText("Milimetros.");
        rdbMl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMlActionPerformed(evt);
            }
        });

        lblResM.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblResM.setText("Resultado.");

        jScrollPane1.setViewportView(txtM);

        txtH.setViewportView(jTextPane3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Horas.");

        rdbMin.setText("Minutos.");
        rdbMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMinActionPerformed(evt);
            }
        });

        rdbSeg.setText("Segundos.");
        rdbSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSegActionPerformed(evt);
            }
        });

        lblResH.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblResH.setText("Resultado.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Kilogramos.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Gramos.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Kg");

        jScrollPane5.setViewportView(txtGr);

        txtKg.setEnabled(false);
        jScrollPane6.setViewportView(txtKg);

        rdbKg.setSelected(true);
        rdbKg.setText("--------->");
        rdbKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbKgActionPerformed(evt);
            }
        });

        rdbGr.setText("<----------");
        rdbGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbMl)
                                            .addComponent(rdbCm)
                                            .addComponent(rdbMin)
                                            .addComponent(rdbSeg)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbGr)
                                            .addComponent(rdbKg))
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblResH)
                                            .addComponent(lblResM)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbCm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbMl)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblResM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbSeg))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblResH)))))
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbKg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbGr))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbCmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCmActionPerformed
          if(rdbCm.isSelected()){
              double m = Double.parseDouble(txtM.getText());
              lblResM.setText(String.valueOf(m*100));
              rdbCm.setSelected(true); 
              rdbMl.setSelected(false);
       } 
    }//GEN-LAST:event_rdbCmActionPerformed

    private void rdbMlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMlActionPerformed
        if(rdbMl.isSelected()){
              double ml = Double.parseDouble(txtM.getText());
              lblResM.setText(String.valueOf(ml*1000));
              rdbCm.setSelected(false); 
              rdbMl.setSelected(true);
       } 
    }//GEN-LAST:event_rdbMlActionPerformed

    private void rdbGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGrActionPerformed
        txtKg.setEnabled(true);
        txtGr.setEnabled(false);
        if(rdbGr.isSelected()){
              double gr = Double.parseDouble(txtGr.getText());
              txtKg.setText(String.valueOf(gr/1000));
              rdbKg.setSelected(false); 
              rdbGr.setSelected(true);
              
       } 
    }//GEN-LAST:event_rdbGrActionPerformed

    private void rdbKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbKgActionPerformed
        txtKg.setEnabled(false);
        txtGr.setEnabled(true);
        if (rdbKg.isSelected()){
            double kg = Double.parseDouble(txtKg.getText());
            txtGr.setText(String.valueOf(kg*1000));
            rdbKg.setSelected(true); 
              rdbGr.setSelected(false);
        }
        
    }//GEN-LAST:event_rdbKgActionPerformed

    private void rdbMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMinActionPerformed
           if(rdbMin.isSelected()){
             double h = Double.parseDouble(jTextPane3.getText());
              lblResH.setText(String.valueOf(h*60));
              rdbMin.setSelected(true); 
              rdbSeg.setSelected(false);
    }//GEN-LAST:event_rdbMinActionPerformed
    }
    private void rdbSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSegActionPerformed
         if(rdbSeg.isSelected()){
             double h = Double.parseDouble(jTextPane3.getText());
              lblResH.setText(String.valueOf(h*3600));
              rdbMin.setSelected(false); 
              rdbSeg.setSelected(true);
    }//GEN-LAST:event_rdbSegActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JLabel lblResH;
    private javax.swing.JLabel lblResM;
    private javax.swing.JRadioButton rdbCm;
    private javax.swing.JRadioButton rdbGr;
    private javax.swing.JRadioButton rdbKg;
    private javax.swing.JRadioButton rdbMin;
    private javax.swing.JRadioButton rdbMl;
    private javax.swing.JRadioButton rdbSeg;
    private javax.swing.JTextPane txtGr;
    private javax.swing.JScrollPane txtH;
    private javax.swing.JTextPane txtKg;
    private javax.swing.JTextPane txtM;
    // End of variables declaration//GEN-END:variables
}
